builds:
  -
    env:
    - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    - freebsd
    - windows
    goarch:
    - amd64
    - arm
archive:
  replacements:
    amd64: x86_64
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: tisba
    name: fritz-tls
  draft: true
  prerelease: false
  disable: false
brew:
  github:
    owner: tisba
    name: taps
  install: bin.install "fritz-tls"
  folder: Formula
  homepage: "https://github.com/tisba/fritz-tls"
  description: "Automate TLS certificate installation for AVM FRITZ!Box"
