builds:
  -
    env:
    - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    - freebsd
    - windows
    goarch:
    - amd64
    - arm
archives:
  - format: zip
    format_overrides:
      - goos: linux
        format: tar.gz
    replacements:
      amd64: x86_64
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: tisba
    name: fritz-tls
  draft: false
  prerelease: false
  disable: false
brews:
  -
    github:
      owner: tisba
      name: homebrew-taps
    install: bin.install "fritz-tls"
    folder: Formula
    homepage: "https://github.com/tisba/fritz-tls"
    description: "Automate TLS certificate installation for AVM FRITZ!Box"
