version: 2
builds:
  -
    env:
    - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    goarch:
    - amd64
    - arm64
    - arm
    goarm:
    - "6"
    - "7"
    flags:
    - -trimpath
    ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}
archives:
  - formats: [ 'zip' ]
    format_overrides:
      - goos: linux
        formats: [ 'tar.gz' ]
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: tisba
    name: fritz-tls
brews:
  -
    repository:
      owner: tisba
      name: homebrew-taps
    install: bin.install "fritz-tls"
    directory: Formula
    homepage: "https://github.com/tisba/fritz-tls"
    description: "Automate TLS certificate installation for AVM FRITZ!Box"
