name: Go

permissions: {}

on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v5
        with:
          go-version-file: "go.mod"

      - name: Print Go Version
        run: go version

      - name: Build
        run: go build -v .

      - name: Test
        run: go test ./...

      - name: gofmt
        run: gofmt -d .

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v4

  goreleaser-check:
    name: GoReleaser Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
        with:
          persist-credentials: false
      - name: Run goreleaser check
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v5
        with:
          version: latest
          args: check
